### ISSUE TITLE
How to convert hashed string to first string?

### ISSUE THREAD

**Issue by BlackIQ** [aghaseyed1/simple-hash-function#1]
hey.
Goodnight.

I used your function and it was really great.
But, how can you convert it to first string?

All in all, it is good.
Have a good night.

Live long and prosper.
Bye.

**Comment by seyedmahdi4** [comment]
hi sir
this is a hash function so it looks like a signature and is one-way .That's why hash was invented
Therefore, access to the first string is not possible with conventional methods (eg Brutforce)
If you need two-way encryption, use the AES algorithm

this function for show a very basic hash method
It is not safe at all ...and it's better don't use it anywhere

good luck and good night

**Comment by BlackIQ** [comment]
Hey man.

Thanks for your information. Lovely!
Really liked it and will use it in apps. Thanks so mush.

May the force be with you.
Goodnight.
Amir.

**Comment by seyedmahdi4** [comment]
you're welcome and good night
